# Generated by Django 3.2.8 on 2024-07-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WindowsLogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_source_name', models.CharField(max_length=100)),
                ('log_type', models.CharField(choices=[('All', 'All'), ('Application', 'Application logs'), ('Security', 'Security logs'), ('Setup', 'Setup logs'), ('System', 'System Logs')], max_length=20)),
                ('log_format', models.CharField(max_length=50)),
                ('ingestion_method', models.CharField(choices=[('WindowsEventForwarding', 'Windows Event Forwarding'), ('PowerShellScripts', 'Windows PowerShell Commands'), ('RemoteEventLogMonitoring', 'Windows Event Log Subscription'), ('WMI', 'WEF Group Policy')], max_length=30)),
                ('collection_interval', models.CharField(max_length=50)),
                ('log_rotation_policy', models.CharField(max_length=100)),
                ('log_retention_period', models.CharField(max_length=100)),
            ],
        ),
    ]
