# Generated by Django 3.2.8 on 2024-07-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowsLogIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingestion_method', models.CharField(choices=[('WindowsEventForwarding', 'Windows Event Forwarding'), ('PowerShellScripts', 'Windows PowerShell Commands'), ('RemoteEventLogMonitoring', 'Windows Event Log Subscription'), ('WMI', 'WEF Group Policy')], max_length=30)),
                ('collection_interval', models.CharField(max_length=50)),
                ('log_rotation_policy', models.CharField(max_length=100)),
                ('log_retention_period', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='windowslogsource',
            name='collection_interval',
        ),
        migrations.RemoveField(
            model_name='windowslogsource',
            name='ingestion_method',
        ),
        migrations.RemoveField(
            model_name='windowslogsource',
            name='log_retention_period',
        ),
        migrations.RemoveField(
            model_name='windowslogsource',
            name='log_rotation_policy',
        ),
    ]
