# Generated by Django 3.2.8 on 2024-07-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0002_auto_20240704_1344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WindowsLogIngestion',
        ),
        migrations.AddField(
            model_name='windowslogsource',
            name='collection_interval',
            field=models.CharField(default=5, max_length=50),
        ),
        migrations.AddField(
            model_name='windowslogsource',
            name='ingestion_method',
            field=models.CharField(choices=[('WindowsEventForwarding', 'Windows Event Forwarding'), ('PowerShellScripts', 'Windows PowerShell Commands'), ('RemoteEventLogMonitoring', 'Windows Event Log Subscription'), ('WMI', 'WEF Group Policy')], default='WindowsEventForwarding', max_length=30),
        ),
        migrations.AddField(
            model_name='windowslogsource',
            name='log_retention_period',
            field=models.CharField(default=5, max_length=100),
        ),
    ]
