# Generated by Django 3.2.8 on 2024-07-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0003_auto_20240705_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowslogsource',
            name='kerberos_keytab',
            field=models.FileField(help_text='Upload Keytab File', null=True, upload_to='keytabs/'),
        ),
        migrations.AddField(
            model_name='windowslogsource',
            name='kerberos_realm',
            field=models.CharField(help_text='Kerberos Realm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='windowslogsource',
            name='kerberos_spn',
            field=models.CharField(help_text='Service Principal Name', max_length=100, null=True),
        ),
    ]
