# Generated by Django 3.2.8 on 2024-07-06 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0004_auto_20240705_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windowslogsource',
            name='kerberos_keytab',
        ),
    ]
