# Generated by Django 3.2.8 on 2024-07-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0005_remove_windowslogsource_kerberos_keytab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windowslogsource',
            name='kerberos_realm',
        ),
        migrations.RemoveField(
            model_name='windowslogsource',
            name='kerberos_spn',
        ),
    ]
