# Generated by Django 3.2.8 on 2024-07-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0007_auto_20240708_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowslogsource',
            name='winrm_host',
            field=models.CharField(default='windows', max_length=100),
        ),
        migrations.AddField(
            model_name='windowslogsource',
            name='winrm_password',
            field=models.CharField(default='....', max_length=100),
        ),
        migrations.AddField(
            model_name='windowslogsource',
            name='winrm_port',
            field=models.IntegerField(default=5985),
        ),
        migrations.AddField(
            model_name='windowslogsource',
            name='winrm_username',
            field=models.CharField(default='username', max_length=100),
        ),
        migrations.AlterField(
            model_name='windowslogsource',
            name='machine_type',
            field=models.CharField(choices=[('Single machine', 'Single machine'), ('Group policy machine', 'Group policy machine')], default='Single machine', max_length=30),
        ),
    ]
