# Generated by Django 3.2.8 on 2024-07-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0008_auto_20240709_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windowslogsource',
            name='collection_interval',
        ),
        migrations.RemoveField(
            model_name='windowslogsource',
            name='log_retention_period',
        ),
        migrations.RemoveField(
            model_name='windowslogsource',
            name='machine_type',
        ),
        migrations.RemoveField(
            model_name='windowslogsource',
            name='winrm_host',
        ),
        migrations.RemoveField(
            model_name='windowslogsource',
            name='winrm_password',
        ),
        migrations.RemoveField(
            model_name='windowslogsource',
            name='winrm_port',
        ),
        migrations.RemoveField(
            model_name='windowslogsource',
            name='winrm_username',
        ),
        migrations.AddField(
            model_name='windowslogsource',
            name='ingestion_mtd',
            field=models.CharField(choices=[('powershell', 'powershell')], default='Powershell', max_length=30),
        ),
    ]
