# Generated by Django 3.2.8 on 2024-07-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0009_auto_20240715_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowslogsource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='windowslogsource',
            name='log_format',
            field=models.CharField(default='JSON', max_length=50),
        ),
    ]
