# Generated by Django 3.2.8 on 2024-07-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0011_windowslogsource_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='windowslogsource',
            name='ingestion_mtd',
            field=models.CharField(choices=[('powershell', 'Powershell')], default='powershell', max_length=30),
        ),
        migrations.RemoveField(
            model_name='windowslogsource',
            name='log_type',
        ),
        migrations.AddField(
            model_name='windowslogsource',
            name='log_type',
            field=models.ManyToManyField(to='log_management_app.LogType'),
        ),
    ]
