# Generated by Django 3.2.8 on 2024-07-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0013_auto_form_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowsFileLogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_source_name', models.CharField(max_length=100)),
                ('log_file_path', models.CharField(max_length=255)),
                ('log_file_type', models.CharField(choices=[('text', 'Text'), ('csv', 'CSV'), ('json', 'JSON'), ('xml', 'XML')], max_length=10)),
                ('collection_frequency', models.CharField(choices=[('5', 'Every 5 minutes'), ('15', 'Every 15 minutes'), ('60', 'Hourly'), ('1440', 'Daily')], max_length=4)),
                ('file_size_limit', models.PositiveIntegerField()),
                ('log_encoding', models.CharField(choices=[('utf-8', 'UTF-8'), ('utf-16', 'UTF-16'), ('iso-8859-1', 'ISO-8859-1'), ('ascii', 'ASCII')], max_length=10)),
                ('rotation_policy', models.CharField(choices=[('size', 'By Size'), ('date', 'By Date'), ('size_date', 'By Size and Date')], max_length=15)),
                ('log_format', models.CharField(choices=[('plain', 'Plain Text'), ('structured', 'Structured'), ('semi_structured', 'Semi-Structured')], max_length=15)),
                ('auth_method', models.CharField(choices=[('none', 'None'), ('basic', 'Basic Auth'), ('windows', 'Windows Authentication')], max_length=10)),
                ('additional_params', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
