# Generated by Django 3.2.8 on 2024-07-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0014_windowsfilelogsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Metric Name')),
            ],
        ),
        migrations.CreateModel(
            name='WindowsPerfLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='IP Address')),
                ('port_number', models.PositiveIntegerField(verbose_name='Port Number')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('collection_interval', models.PositiveIntegerField(verbose_name='Collection Interval (seconds)')),
                ('retention_period', models.PositiveIntegerField(verbose_name='Data Retention Period (days)')),
                ('log_format', models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('csv', 'CSV')], max_length=10, verbose_name='Log Format')),
                ('notifications', models.BooleanField(default=False, verbose_name='Enable Notifications')),
                ('performance_metrics', models.ManyToManyField(help_text='Select the metrics to collect', to='log_management_app.PerformanceMetric', verbose_name='Performance Metrics')),
            ],
        ),
    ]
