# Generated by Django 3.2.8 on 2024-07-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0016_windowsactivedirectorylogsource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windowslogsource',
            name='log_format',
        ),
    ]
