# Generated by Django 3.2.8 on 2024-07-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0017_remove_windowslogsource_log_format'),
        ('log_management_app', '0018_auto_populate_performance_metrics'),
    ]

    operations = [
    ]
