# Generated by Django 5.0.7 on 2024-07-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0021_webserverlogfileupload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('version', models.IntegerField()),
                ('qualifiers', models.IntegerField(blank=True, null=True)),
                ('level', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=50)),
                ('opcode', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=50)),
                ('record_id', models.IntegerField()),
                ('provider_name', models.CharField(max_length=255)),
                ('provider_id', models.CharField(max_length=255)),
                ('log_name', models.CharField(max_length=50)),
                ('process_id', models.IntegerField()),
                ('thread_id', models.IntegerField()),
                ('machine_name', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('account_domain', models.CharField(max_length=255)),
                ('account_logon_id', models.CharField(max_length=255)),
                ('logon_type', models.IntegerField()),
                ('logon_process', models.CharField(max_length=255)),
                ('authentication_package', models.CharField(max_length=255)),
                ('workstation_name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('ip_port', models.IntegerField()),
                ('object_name', models.CharField(max_length=255)),
                ('object_type', models.CharField(max_length=255)),
                ('handle_id', models.CharField(max_length=255)),
                ('access_mask', models.CharField(max_length=255)),
                ('privileges', models.CharField(max_length=255)),
                ('restricted_sid_count', models.IntegerField()),
                ('description', models.TextField()),
                ('time_created', models.DateTimeField()),
                ('correlation', models.JSONField(blank=True, null=True)),
                ('execution', models.JSONField()),
                ('channel', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=255)),
                ('opcode_value', models.IntegerField()),
                ('severity', models.CharField(max_length=50)),
                ('user_data', models.JSONField()),
            ],
        ),
    ]
