# Generated by Django 5.0.7 on 2024-07-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0023_remove_securitylog_correlation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitylog',
            name='account_domain',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='account_logon_id',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='execution',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='level',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='log_name',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='machine_name',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='opcode',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='opcode_value',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='process_id',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='record_id',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='task',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='thread_id',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='version',
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='access_mask',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='authentication_package',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='handle_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='ip_port',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='logon_process',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='logon_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='object_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='object_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='privileges',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='restricted_sid_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='user_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='workstation_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
