# Generated by Django 5.0.7 on 2024-07-29 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0024_remove_securitylog_account_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
