# Generated by Django 5.0.7 on 2024-07-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0026_rename_ip_port_securitylog_event_id_and_more'),
    ]

    operations = [
    ]
