# Generated by Django 5.0.7 on 2024-07-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0027_auto_20240729_1254'),
    ]

    operations = [
    ]
