# Generated by Django 4.2.11 on 2024-07-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0022_windowslogsource_collection_interval_and_more'),
        ('log_management_app', '0029_auto_20240729_1300'),
    ]

    operations = [
    ]
