# Generated by Django 4.2.11 on 2024-07-29 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0030_merge_20240729_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowslogsource',
            name='activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='windowslogsource',
            name='hostname_ip_address',
            field=models.CharField(default='localhost', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='windowslogsource',
            name='status',
            field=models.CharField(choices=[('Online', 'Active'), ('Offline', 'Inactive')], default='Offline', max_length=10),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='event_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
