# Generated by Django 4.2.11 on 2024-07-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0032_remove_windowsfilelogsource_collection_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windowsfilelogsource',
            name='additional_params',
        ),
        migrations.RemoveField(
            model_name='windowsfilelogsource',
            name='auth_method',
        ),
        migrations.RemoveField(
            model_name='windowsfilelogsource',
            name='log_format',
        ),
        migrations.AddField(
            model_name='windowsfilelogsource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='windowsfilelogsource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
