# Generated by Django 4.2.11 on 2024-07-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0033_remove_windowsfilelogsource_additional_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowsfilelogsource',
            name='activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='windowsfilelogsource',
            name='status',
            field=models.CharField(choices=[('Online', 'Active'), ('Offline', 'Inactive')], default='Offline', max_length=10),
        ),
    ]
