# Generated by Django 4.2.11 on 2024-07-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0035_remove_windowsperflogs_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowsperflogs',
            name='log_source_name',
            field=models.CharField(max_length=100),
        ),
    ]
