# Generated by Django 4.2.11 on 2024-07-31 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0039_alter_windowsperflogs_log_source_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windowsperflogs',
            name='log_source_name',
        ),
    ]
