# Generated by Django 4.2.11 on 2024-07-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0041_windowsperflogs_log_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowsperflogs',
            name='log_source_name',
            field=models.CharField(default='log_source', max_length=100),
        ),
    ]
