# Generated by Django 4.2.11 on 2024-07-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0043_remove_windowsactivedirectorylogsource_domain_controller_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowsactivedirectorylogsource',
            name='collection_mtd',
            field=models.CharField(default='AD logs', max_length=50),
        ),
        migrations.AddField(
            model_name='windowsfilelogsource',
            name='collection_mtd',
            field=models.CharField(default='Files streaming', max_length=50),
        ),
        migrations.AddField(
            model_name='windowslogsource',
            name='collection_mtd',
            field=models.CharField(default='Log streaming', max_length=50),
        ),
        migrations.AddField(
            model_name='windowsperflogs',
            name='collection_mtd',
            field=models.CharField(default='perf logs', max_length=50),
        ),
    ]
