# Generated by Django 4.2.11 on 2024-08-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0048_macfilelogsource_maclogtype_macperformancemetric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldaplogsource',
            name='os_type',
            field=models.CharField(default='Linux', max_length=50),
        ),
        migrations.AddField(
            model_name='linuxfilelogsource',
            name='os_type',
            field=models.CharField(default='Linux', max_length=50),
        ),
        migrations.AddField(
            model_name='linuxlogsource',
            name='os_type',
            field=models.CharField(default='Linux', max_length=50),
        ),
        migrations.AddField(
            model_name='linuxperflogs',
            name='os_type',
            field=models.CharField(default='Linux', max_length=50),
        ),
        migrations.AddField(
            model_name='macfilelogsource',
            name='os_type',
            field=models.CharField(default='Mac', max_length=50),
        ),
        migrations.AddField(
            model_name='maclogsource',
            name='os_type',
            field=models.CharField(default='Mac', max_length=50),
        ),
        migrations.AddField(
            model_name='macperflogs',
            name='os_type',
            field=models.CharField(default='Mac', max_length=50),
        ),
        migrations.AddField(
            model_name='opendirlogsource',
            name='os_type',
            field=models.CharField(default='Mac', max_length=50),
        ),
        migrations.AddField(
            model_name='windowsactivedirectorylogsource',
            name='os_type',
            field=models.CharField(default='Windows', max_length=50),
        ),
        migrations.AddField(
            model_name='windowsfilelogsource',
            name='os_type',
            field=models.CharField(default='Windows', max_length=50),
        ),
        migrations.AddField(
            model_name='windowslogsource',
            name='os_type',
            field=models.CharField(default='Windows', max_length=50),
        ),
        migrations.AddField(
            model_name='windowsperflogs',
            name='os_type',
            field=models.CharField(default='Windows', max_length=50),
        ),
    ]
