# Generated by Django 4.2.11 on 2024-08-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0060_alert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
