# Generated by Django 4.2.11 on 2024-08-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0062_windowsalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowslogtype',
            name='name',
            field=models.CharField(choices=[('system', 'System'), ('security', 'Security'), ('setup', 'Setup'), ('application', 'Application')], max_length=20, unique=True),
        ),
    ]
