# Generated by Django 4.2.11 on 2024-08-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0064_remove_windowslogsource_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='windowsfilelogsource',
            old_name='log_file_type',
            new_name='log_format',
        ),
        migrations.RemoveField(
            model_name='windowsfilelogsource',
            name='file_size_limit',
        ),
        migrations.AddField(
            model_name='windowsfilelogsource',
            name='log_type',
            field=models.ManyToManyField(to='log_management_app.windowslogtype'),
        ),
    ]
