# Generated by Django 4.2.11 on 2024-08-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0065_rename_log_file_type_windowsfilelogsource_log_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowsfilelogsource',
            name='ingestion_mtd',
            field=models.CharField(choices=[('powershell', 'Powershell')], default='powershell', max_length=30),
        ),
    ]
