# Generated by Django 4.2.11 on 2024-08-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0068_webserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='apacheserverlogfilestream',
            name='server_type',
            field=models.CharField(default='Apache', max_length=50),
        ),
        migrations.AddField(
            model_name='apacheserverlogstream',
            name='server_type',
            field=models.CharField(default='Apache', max_length=50),
        ),
        migrations.AddField(
            model_name='apacheserverperflogs',
            name='server_type',
            field=models.CharField(default='Apache', max_length=50),
        ),
        migrations.AddField(
            model_name='iisserverlogfilestream',
            name='server_type',
            field=models.CharField(default='IIS', max_length=50),
        ),
        migrations.AddField(
            model_name='iisserverlogstream',
            name='server_type',
            field=models.CharField(default='IIS', max_length=50),
        ),
        migrations.AddField(
            model_name='iisserverperflogs',
            name='server_type',
            field=models.CharField(default='IIS', max_length=50),
        ),
        migrations.AddField(
            model_name='nginxserverlogfilestream',
            name='server_type',
            field=models.CharField(default='Nginx', max_length=50),
        ),
        migrations.AddField(
            model_name='nginxserverlogstream',
            name='server_type',
            field=models.CharField(default='Nginx', max_length=50),
        ),
        migrations.AddField(
            model_name='nginxserverperflogs',
            name='server_type',
            field=models.CharField(default='Nginx', max_length=50),
        ),
    ]
