# Generated by Django 5.1.2 on 2024-10-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0072_alter_windowslogtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowslogtype',
            name='name',
            field=models.CharField(choices=[('system', 'System'), ('security', 'Security'), ('setup', 'Setup'), ('application', 'Application')], max_length=20, unique=True),
        ),
    ]
