# Generated by Django 5.1.2 on 2024-11-11 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0074_logentry_anomaly_uploadedlog_logentry_log_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedlog',
            old_name='log_file',
            new_name='file',
        ),
    ]
