# Generated by Django 5.1.2 on 2024-11-11 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0076_remove_uploadedlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='log_file',
        ),
        migrations.DeleteModel(
            name='Anomaly',
        ),
    ]
