# Generated by Django 5.1.2 on 2024-11-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0078_uploadedlog_source_name_alter_uploadedlog_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedLog',
            new_name='WindowsLogFile',
        ),
    ]
