# Generated by Django 5.1.2 on 2024-11-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0079_rename_uploadedlog_windowslogfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowsADLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=20, null=True)),
                ('os_type', models.CharField(default='WindowsAD', max_length=50)),
                ('file', models.FileField(upload_to='uploaded_logs/windowsAD/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='windowslogsource',
            name='log_type',
        ),
        migrations.RemoveField(
            model_name='windowsperflogs',
            name='performance_metrics',
        ),
        migrations.AddField(
            model_name='windowslogfile',
            name='os_type',
            field=models.CharField(default='Windows', max_length=50),
        ),
        migrations.DeleteModel(
            name='WindowsFileLogSource',
        ),
        migrations.DeleteModel(
            name='WindowsLogSource',
        ),
        migrations.DeleteModel(
            name='WindowsPerfLogs',
        ),
        migrations.DeleteModel(
            name='WindowsPerformanceMetric',
        ),
    ]
