# Generated by Django 5.1.2 on 2024-11-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0080_windowsadlogfile_remove_windowslogsource_log_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinuxLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=20, null=True)),
                ('os_type', models.CharField(default='WindowsAD', max_length=50)),
                ('file', models.FileField(upload_to='uploaded_logs/windowsAD/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
