# Generated by Django 5.1.2 on 2024-11-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0081_linuxlogfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=20, null=True)),
                ('os_type', models.CharField(default='mac', max_length=50)),
                ('file', models.FileField(upload_to='uploaded_logs/mac/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LDAPLogSource',
        ),
        migrations.RemoveField(
            model_name='linuxfilelogsource',
            name='log_type',
        ),
        migrations.RemoveField(
            model_name='linuxlogsource',
            name='log_type',
        ),
        migrations.RemoveField(
            model_name='linuxperflogs',
            name='performance_metrics',
        ),
        migrations.RemoveField(
            model_name='macperflogs',
            name='performance_metrics',
        ),
        migrations.DeleteModel(
            name='WindowsActiveDirectoryLogSource',
        ),
        migrations.DeleteModel(
            name='WindowsLogType',
        ),
        migrations.AlterField(
            model_name='linuxlogfile',
            name='file',
            field=models.FileField(upload_to='uploaded_logs/linux/'),
        ),
        migrations.AlterField(
            model_name='linuxlogfile',
            name='os_type',
            field=models.CharField(default='Linux', max_length=50),
        ),
        migrations.DeleteModel(
            name='LinuxFileLogSource',
        ),
        migrations.DeleteModel(
            name='LinuxLogSource',
        ),
        migrations.DeleteModel(
            name='LinuxLogType',
        ),
        migrations.DeleteModel(
            name='LinuxPerfLogs',
        ),
        migrations.DeleteModel(
            name='LinuxPerformanceMetric',
        ),
        migrations.DeleteModel(
            name='MacPerfLogs',
        ),
    ]
