# Generated by Django 5.1.2 on 2024-11-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0084_iislogfile_nginxlogfile_delete_iislogfileuploadform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MongoLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=20, null=True)),
                ('os_type', models.CharField(default='mongo', max_length=50)),
                ('file', models.FileField(upload_to='uploaded_logs/mongo/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MysqlLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=20, null=True)),
                ('os_type', models.CharField(default='mysql', max_length=50)),
                ('file', models.FileField(upload_to='uploaded_logs/mysql/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostgresLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=20, null=True)),
                ('os_type', models.CharField(default='postgres', max_length=50)),
                ('file', models.FileField(upload_to='uploaded_logs/postgres/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MongodbLogFileStream',
        ),
        migrations.DeleteModel(
            name='MongodbLogStream',
        ),
        migrations.DeleteModel(
            name='MongodbPerfLogs',
        ),
        migrations.DeleteModel(
            name='MongoLogFileUploadForm',
        ),
        migrations.DeleteModel(
            name='MysqlLogFileStream',
        ),
        migrations.DeleteModel(
            name='MysqlLogFileUploadForm',
        ),
        migrations.DeleteModel(
            name='MysqlLogStream',
        ),
        migrations.DeleteModel(
            name='MysqlPerfLogs',
        ),
        migrations.DeleteModel(
            name='PostgresLogFileStream',
        ),
        migrations.DeleteModel(
            name='PostgresLogFileUploadForm',
        ),
        migrations.DeleteModel(
            name='PostgresLogStream',
        ),
        migrations.DeleteModel(
            name='PostgresPerfLogs',
        ),
    ]
