# Generated by Django 5.1.2 on 2024-11-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0085_mongologfile_mysqllogfile_postgreslogfile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=20, null=True)),
                ('anomaly', models.CharField(blank=True, max_length=20, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
