# Generated by Django 5.1.2 on 2024-11-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0086_anomaly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_title', models.CharField(max_length=30)),
                ('alert_desc', models.CharField(max_length=100)),
                ('alert_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=100)),
                ('detected_at', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='WindowsAlert',
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='anomaly',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
