# Generated by Django 5.1.2 on 2024-11-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0087_alert_delete_windowsalert_alter_anomaly_anomaly'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_processed', models.DateTimeField()),
            ],
        ),
    ]
