# Generated by Django 5.1.2 on 2024-11-19 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0091_rename_timestamp_logentry_timecreated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anomaly',
        ),
        migrations.AddField(
            model_name='logentry',
            name='batch_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='event_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='last_processed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
