# Generated by Django 5.1.2 on 2024-11-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0092_delete_anomaly_logentry_batch_id_logentry_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowslogfile',
            name='source',
            field=models.CharField(default='Windows', max_length=255),
        ),
    ]
