# Generated by Django 5.1.2 on 2024-11-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0093_windowslogfile_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='alert_desc',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='detected_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='alert_level',
        ),
        migrations.AddField(
            model_name='alert',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='None', max_length=10),
        ),
    ]
