# Generated by Django 5.1.2 on 2024-11-20 01:28

from django.db import migrations

def set_default_user(apps, schema_editor):
    LogEntry = apps.get_model('log_management_app', 'LogEntry')
    User = apps.get_model('user_management_app', 'User')
    
    # You can choose a specific user, or you can get the first user if no user is found
    default_user = User.objects.first()
    if default_user:
        LogEntry.objects.filter(user__isnull=True).update(user=default_user)

class Migration(migrations.Migration):
    dependencies = [
        ('log_management_app', '0105_alter_alert_user_alter_logentry_user'),
    ]

    operations = [
        migrations.RunPython(set_default_user),
    ]
