# Generated by Django 5.1.2 on 2024-11-20 01:36

import django.db.models.deletion
import log_management_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0106_auto_20241120_0128'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(default=log_management_app.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='alerts_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='user',
            field=models.ForeignKey(default=log_management_app.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
