# Generated by Django 5.1.2 on 2024-11-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0109_alter_alert_user_alter_logentry_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessLog',
        ),
    ]
