# Generated by Django 4.2.11 on 2024-08-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0004_rename_full_name_user_first_name_user_account_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Superuser', 'Superuser'), ('Log Analyst', 'Log Analyst'), ('Operator', 'Operator'), ('Viewer', 'Viewer')], default='Select Role', max_length=50),
        ),
    ]
