# Generated by Django 5.1.2 on 2024-11-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0005_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='security_answer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='security_question',
        ),
    ]
