# Generated by Django 4.2.11 on 2024-08-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_and_notifications_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WindowsAlert',
        ),
    ]
